-- packer
require("user.plugins")

-- user configuration
require("user.keymaps")
require("user.autocommands")
require("user.colorscheme")
require("user.options")

-- plugins
require("user.alpha")
require("user.autopairs")
require("user.barbecue")
require("user.bufferline")
require("user.cmp")
require("user.dap")
require("user.comment")
require("user.gitsigns")
require("user.hlslens")
require("user.hop")
require("user.illuminate")
require("user.indentline")
require("user.iswap")
require("user.jaq")
require("user.leetbuddy")
require("user.lualine")
require("user.mini")
require("user.notify")
require("user.nvim-colorizer")
require("user.nvim-toggler")
require("user.nvim-tree")
require("user.nvim-webdev-icons")
require("user.project")
require("user.surround")
require("user.symbols-outline")
require("user.telescope")
require("user.todo-comments")
require("user.toggleterm")
require("user.treesitter-context")
require("user.treesitter")
require("user.whichkey")

-- lsp config folder
require("user.lsp")
