require("plugins/alpha")
require("plugins/bufferline")
require("plugins/cinnamon")
require("plugins/cmp")
require("plugins/comment")
require("plugins/gitsigns")
require("plugins/hlslens")
require("plugins/hop")
require("plugins/indentline")
require("plugins/jaq")
require("plugins/lualine")
require("plugins/notify")
require("plugins/nvim-tree")
require("plugins/plugins")
require("plugins/project")
require("plugins/smart-pairs")
require("plugins/sniprun")
require("plugins/telescope")
require("plugins/toggleterm")
require("plugins/treesitter-context")
require("plugins/treesitter")
require("plugins/whichkey")
require("plugins/nvim-colorizer")

-- mini.nvim --
require("plugins/surround").setup({})
